<?php

namespace Database\Seeders;

use App\EnumTypes\Accessory\AccessoryEdition;
use App\Models\Game\Settings\Accessory;
use App\Models\Game\Settings\AccessoryCollection;
use App\Models\Game\Settings\AccessoryRarityType;
use App\Models\Game\Settings\AccessoryType;
use App\Models\Game\Settings\CollectionPuberType;
use Exception;
use Illuminate\Database\Seeder;

class AccessoriesCollectionFoundersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     * @throws Exception
     */
    public function run(): void
    {
        $this->addLimitedAccessories();
    }

    /**
     * @throws Exception
     */
    private function addLimitedAccessories(){
        try {
            $accessories = [
                // ACCESSORIES BAD BIKER
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Helmet Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Glasses Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Beard Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shirt Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Bad Biker',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Bad Biker')->first()->id,
                ],

                // ACCESSORIES RAPPER
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Cap Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Glasses Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Golden Tooth Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Shirt Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Rapper',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Rapper')->first()->id,
                ],

                // ACCESSORIES NERD
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Hair Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Glasses Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Separated Tooth Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Pants Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe Nerd',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Nerd')->first()->id,
                ],

                //ACCESSORIES MAD SCIENTIST
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Hair Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Glasses Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Moustache Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shirt Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Mad Scientist',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mad Scientist')->first()->id,
                ],

                //ACCESSORIES COWBOY
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Hat Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eye Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Straw In Mouth Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe Cowboy',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Cowboy')->first()->id,
                ],

                //ACESSORIES SWIMMER
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Cap Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Glasses Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Snorkel Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Bronzed Body Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Pants Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Duck Foot Swimmer',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Swimmer')->first()->id,
                ],

                //ACCESSORIES WIZARD
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Cap Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Glasses Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Wart Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Pants Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Wizard',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Wizard')->first()->id,
                ],

                //ACCESSORIES PIRATE
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Scarf Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Eye-patch Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Broken Tooth Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe Pirate',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Pirate')->first()->id,
                ],

                //ACCESSORIES MOBSTER
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Cap Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Glasses Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Cigar Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Pants Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Mobster',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mobster')->first()->id,
                ],

                //ACCESSORIES DETECTIVE
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Cap Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Monocle Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Smoking Pipe Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Detective',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Detective')->first()->id,
                ],

                //ACCESSORIES DISGUISED
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Cap Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eyebrow-glasses Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Mustache-nose Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Pants Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe Disguised',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Disguised')->first()->id,
                ],

                //ACCESSORIES MUSHROOM
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Cap Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eyebrow-glasses Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Slobber-nose Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shirt Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Pants Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Mushroom',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Mushroom')->first()->id,
                ],

                //ACCESSORIES WAITER
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Hair Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eye Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Moustache Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shirt Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Shoe Waiter',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Waiter')->first()->id,
                ],

                // ACCESSORIES ROBOT
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Antenna Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eye Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Mouth Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Torso Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Pants Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe Robot',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('Robot')->first()->id,
                ],

                //ACCESSORIES KING
                [
                    'type_id' => AccessoryType::query()->whereName('Head')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Epic')->first()->id,
                    'name' => 'Crown King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Eye')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Common')->first()->id,
                    'name' => 'Eye with eyebrow King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Face')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Moustache King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shirt')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Robe King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Pants')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Pants King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],

                [
                    'type_id' => AccessoryType::query()->whereName('Shoe')->first()->id,
                    'rarity_id' => AccessoryRarityType::query()->whereName('Rare')->first()->id,
                    'name' => 'Shoe King',
                    'description' => null,
                    'available_for_sale' => false,
                    'available_quantity' => 0,
                    'is_unlimited' => false,
                    'skills_id' => null,
                    'modifier' => null,
                    'is_free' => false,
                    'edition' => AccessoryEdition::SpecialEdition,
                    'accessory_collections_id' => AccessoryCollection::query()->whereName('Founders')->first()->id,
                    'collection_puber_types_id' => CollectionPuberType::query()->whereName('King')->first()->id,
                ],
            ];

            foreach ($accessories as $accessory){
                $accessory = (object)$accessory;

                Accessory::query()
                    ->firstOrCreate([
                        'name' => $accessory->name
                    ], [
                        'name' => $accessory->name,
                        'description' => $accessory->description
                    ]);
            }
        }catch (Exception $exception){
            print_r(__FUNCTION__ . PHP_EOL);
            print_r($exception->getMessage() . PHP_EOL);
            throw $exception;
        }
    }
}
