version: '3'

networks:
  pub:
    driver: bridge

services:
  # image project
  pubgame_api:
    build:
      args:
        user: gabrielteste
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    ports:
      - "9004:8000"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - queue
    networks:
      - pub

  #NODE
  node:
    image: node:14.17.3
    container_name: node_pub
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ['npm']

  #Host
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_pub
    restart: unless-stopped
    ports:
      - "7000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      pub:

  #Database
  mysql:
    image: mysql:8
    container_name: mysql_pub
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql

  # queue
  queue:
    build:
      args:
        user: gabrielteste
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - pub

  # redis
  redis:
    image: redis:latest
    networks:
      - pub
