version: "3.7"
services:
  # image project
  pubgame_api:
    container_name: pubgame_api_app_laravel
    build:
      args:
        user: gabriel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - queue
    networks:
      - pubnetwork

  # nginx
  nginx:
    container_name: pubgame_nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - pubnetwork

  # db mysql
  mysql:
    container_name: pubgame_mysql
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: dhxy8hkIDP&Y
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - pubnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - "8081:8081"
    environment:
      - PMA_ARBITRARY=1

  # queue
  queue:
    build:
      args:
        user: gabriel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: pubgame_queue
    restart: unless-stopped
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - pubnetwork

  # redis
  redis:
    container_name: pubgame_redis
    image: redis:latest
    networks:
      - pubnetwork

networks:
  pubnetwork:
    driver: bridge
